### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by iiegor** [gcr/xat-client#1]
How i execute the node.js ? The client.js launch an error!
How i compile the as3 file?
This xat-client is for create a private server of xat or what

**Comment by gcr** [comment]
Unfortunately, this probably isn't what you want. It's just a small library that allows you to write nodejs programs that interact with certain existing chat rooms (ie. write bots or whatever). It hasn't been updated in years.

See http://nodejs.org/ for more information about how to run Node programs. A small read-only client is in client.js.

**Comment by iiegor** [comment]
Please, Can you explain to me for what serves the code of chat.as3?

(Sorry for my english, google translator)

**Comment by gcr** [comment]
If I remember right, 'chat.as3' is just the decompiled source code
inside of chat445.swf. That means Xat serves it, so you don't need it.
The only things you need are xat-client.js and client.js. Xat's web
server is what serves chat445.swf, loader.as3, flash-xmlsocket.js, and
chat.as3. I only included those in the repository for debugging
convenience.

Xat might have changed its system though, so this code probably doesn't work.
